import javax.swing.JOptionPane;

public class GenusTendCalculator extends javax.swing.JFrame {

    /**
     * Creates new form GenusTendCalculator
     */
    public GenusTendCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calculateBt = new javax.swing.JButton();
        saveBt = new javax.swing.JButton();
        quitBt = new javax.swing.JButton();
        fileInputBt = new javax.swing.JButton();
        selectionMode = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        fAText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        faText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        inputMode = new javax.swing.JComboBox();
        AAFreqText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        AaFreqText = new javax.swing.JTextField();
        aaFreqText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        AAfRateText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        AafRateText = new javax.swing.JTextField();
        aafRateText = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        totalGen = new javax.swing.JTextField();
        resultArea = new javax.swing.JScrollPane();
        resultText = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        capitaText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        natalityText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        mortalityText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        calculateBt.setText("Calculate");
        calculateBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateBtActionPerformed(evt);
            }
        });

        saveBt.setText("Save Results");
        saveBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtActionPerformed(evt);
            }
        });

        quitBt.setText("Quit");
        quitBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitBtActionPerformed(evt);
            }
        });

        fileInputBt.setText("Input From File");
        fileInputBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileInputBtActionPerformed(evt);
            }
        });

        selectionMode.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        selectionMode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selection Against Recessive", "Selection Against Dominant", "Selection Against Both But not Heterozygotes", "Free Mode" }));

        jLabel1.setText("Initial allele Frequency A:");

        fAText.setText("0.5");

        jLabel2.setText("Initial allele Frequency a:");

        faText.setText("0.5");

        jLabel3.setText("Initial gene Frequency AA:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Natural Selection Mode:");

        jLabel6.setText("Data Input Mode:");

        inputMode.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        inputMode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Input Allele Frequency", "Input Gene Frequency" }));

        AAFreqText.setText("0.25");

        jLabel7.setText("Initial gene Frequency Aa:");

        jLabel8.setText("Initial gene Frequency aa:");

        AaFreqText.setText("0.5");

        aaFreqText.setText("0.25");

        jLabel9.setText("aa Servival Rate:");

        AAfRateText.setText("1");

        jLabel10.setText("AA Servival Rate:");

        jLabel11.setText("Aa Servival Rate:");

        AafRateText.setText("1");

        aafRateText.setText("1");

        jLabel13.setText("# of simu generations:");

        totalGen.setText("100");

        resultText.setColumns(20);
        resultText.setRows(5);
        resultText.setText("Simulation Result:");
        resultArea.setViewportView(resultText);

        jLabel14.setText("Initial Capita:");

        capitaText.setText("2000");

        jLabel5.setText("Natality:");

        jLabel12.setText("Mortality:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saveBt, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fileInputBt, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calculateBt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quitBt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(resultArea)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel6)
                                .addComponent(jLabel14)
                                .addComponent(capitaText, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(selectionMode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inputMode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(natalityText, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(24, 24, 24)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(mortalityText)))))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(totalGen, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(faText, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fAText, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(AAFreqText, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(AaFreqText, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(aaFreqText, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(aafRateText, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(AafRateText, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(AAfRateText, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(5, 5, 5)
                        .addComponent(fAText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(faText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AAFreqText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AaFreqText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(0, 0, 0)
                        .addComponent(aaFreqText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AAfRateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AafRateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aafRateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calculateBt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalGen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quitBt)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(resultArea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(selectionMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(inputMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel5)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(capitaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(natalityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mortalityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addComponent(saveBt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fileInputBt)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateBtActionPerformed
        // TODO add your handling code here:
        if(inputMode.getSelectedIndex() == 0)
            getAlleleFreqData();
        else if(inputMode.getSelectedIndex() == 1)
            getGeneFreqData();
        
        getGenusData();
        calculateResult();
    }//GEN-LAST:event_calculateBtActionPerformed

    private void quitBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitBtActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Quiting the app, goodbye!");
        System.exit(0);
    }//GEN-LAST:event_quitBtActionPerformed

    private void fileInputBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileInputBtActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Waiting to be implemented in the near version!!");
    }//GEN-LAST:event_fileInputBtActionPerformed

    private void saveBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(this, "Waiting to be implemented in the near version!!");
    }//GEN-LAST:event_saveBtActionPerformed

    private void getGeneFreqData(){
         try {
            fAA0 = Double.parseDouble(AAFreqText.getText());
            fAa0 = Double.parseDouble(AaFreqText.getText());
            faa0 = Double.parseDouble(aaFreqText.getText());
            
            fA0 = (fAA0 * 2 + fAa0) / 2.0;
            fa0 = (faa0 * 2 + fAa0) / 2.0;
            
            fAText.setText(String.format("%2.6f ", fA0));
            faText.setText(String.format("%2.6f ", fa0));
            
            fRateaa = Double.parseDouble(aafRateText.getText());
            fRateAa = Double.parseDouble(AafRateText.getText());
            fRateAA = Double.parseDouble(AAfRateText.getText());
            nthGen = Integer.parseInt(totalGen.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid information may be entered!!",
                    "Error 11: Invalid Inforamtion", JOptionPane.WARNING_MESSAGE);
        }//end try-catch
    }//end method
    
    private void getAlleleFreqData() {
        try {
            fA0 = Double.parseDouble(fAText.getText());
            fa0 = Double.parseDouble(faText.getText());
            
            AAFreqText.setText(String.format("%2.6f", fA0 * fA0));
            AaFreqText.setText(String.format("%2.6f", 2 * fA0 * fa0));
            AaFreqText.setText(String.format("%2.6f ", fa0 * fa0));
            
            fRateaa = Double.parseDouble(aafRateText.getText());
            fRateAa = Double.parseDouble(AafRateText.getText());
            fRateAA = Double.parseDouble(AAfRateText.getText());
            nthGen = Integer.parseInt(totalGen.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid information may be entered!!",
                    "Error 11: Invalid Inforamtion", JOptionPane.WARNING_MESSAGE);
        }//end try-catch
    }//end method

    private void getGenusData(){
        
        try {
            totalCap0 = Integer.parseInt(capitaText.getText());
            double natality = Double.parseDouble(natalityText.getText());
            double mortality = Double.parseDouble(mortalityText.getText());
            gchangeRate = natality - mortality + 1.0;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid information may be entered!!",
                    "Error 11: Invalid Inforamtion", JOptionPane.WARNING_MESSAGE);
        }//end try-catch
        
    }//end method: Get initial data of the genus.
    
    private void calculateResult() {
        if ((selectionMode.getSelectedIndex() == 0)) {
            ressesive = new SimuAgRessesive(nthGen, fA0, fa0, fRateaa, totalCap0, gchangeRate);
            System.out.println(gchangeRate);
            ressesive.runSimulation();
            String result = ressesive.getSimuResult();
            resultText.setText(result);
        }//end if: Against resessive, input alleleFreq
        else if (selectionMode.getSelectedIndex() == 1) {
            dominant = new SimuAgDominant(nthGen, fA0, fa0, fRateAA, totalCap0, gchangeRate);
            dominant.runSimulation();
            String result = dominant.getSimuResult();
            resultText.setText(result);
        }//end else if: Against dominant, input alleleFreq
        else if (selectionMode.getSelectedIndex() == 2) {
            both = new SimuAgBoth(nthGen, fA0, fa0, fRateAA, fRateaa, totalCap0, gchangeRate);
            both.runSimulation();
            String result = both.getSimuResult();
            resultText.setText(result);
        }//end else if: Against both, input alleleFreq
        else if (selectionMode.getSelectedIndex() == 3) {
            free = new FreeMode(nthGen, fA0, fa0, fRateAA, fRateAa, fRateaa, totalCap0, gchangeRate);
            free.runSimulation();
            String result = free.getSimuResult();
            resultText.setText(result);
        }//end else if: Against all 3, input alleleFreq
    }//end method: Read corresponding data from user based on different situations.   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenusTendCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenusTendCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenusTendCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenusTendCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenusTendCalculator().setVisible(true);
            }
        });
    }//end main
    
    private double fA0, fa0, fAA0, fAa0, faa0, fRateAA, fRateAa, fRateaa, gchangeRate;
    //gchangeRate for the genus.
    private int nthGen, totalCap0;
    private SimuAgRessesive ressesive;
    private SimuAgDominant dominant;
    private SimuAgBoth both;
    private FreeMode free;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AAFreqText;
    private javax.swing.JTextField AAfRateText;
    private javax.swing.JTextField AaFreqText;
    private javax.swing.JTextField AafRateText;
    private javax.swing.JTextField aaFreqText;
    private javax.swing.JTextField aafRateText;
    private javax.swing.JButton calculateBt;
    private javax.swing.JTextField capitaText;
    private javax.swing.JTextField fAText;
    private javax.swing.JTextField faText;
    private javax.swing.JButton fileInputBt;
    private javax.swing.JComboBox inputMode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mortalityText;
    private javax.swing.JTextField natalityText;
    private javax.swing.JButton quitBt;
    private javax.swing.JScrollPane resultArea;
    private javax.swing.JTextArea resultText;
    private javax.swing.JButton saveBt;
    private javax.swing.JComboBox selectionMode;
    private javax.swing.JTextField totalGen;
    // End of variables declaration//GEN-END:variables
}
