package ProjectFrames;

import BasicEntities.Disease;
import DBLinkers.DiseaseLinker;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class DiseaseFrame extends javax.swing.JFrame{

    /**
     * Creates new form DiseaseFrame
     */
    public DiseaseFrame() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }//end cons

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        ChineseNameField = new javax.swing.JTextField();
        seriousLevelComboBox = new javax.swing.JComboBox<String>();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptField = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        chineseDescripField = new javax.swing.JTextArea();
        recordBt = new javax.swing.JButton();
        updateBt = new javax.swing.JButton();
        queryBt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Disease Name:");

        jLabel2.setText("Chinese Name:");
        jLabel2.setToolTipText("Input the Chinese name of the disease, if it has.");

        jLabel3.setText("Description:");

        jLabel4.setText("Chinese Description:");

        jLabel5.setText("Serious Level:");

        nameField.setText("myocardial infarction");

        ChineseNameField.setText("心肌梗塞");

        seriousLevelComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1 - Does not matter too much", "2 - Cause long term effects", "3 - Cause death in long term", "4 - Cause bad effects shortly", "5 - Leads to death quickly" }));

        descriptField.setColumns(20);
        descriptField.setRows(5);
        jScrollPane1.setViewportView(descriptField);

        chineseDescripField.setColumns(20);
        chineseDescripField.setRows(5);
        jScrollPane2.setViewportView(chineseDescripField);

        recordBt.setText("Record");
        recordBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordBtActionPerformed(evt);
            }
        });

        updateBt.setText("Update");
        updateBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtActionPerformed(evt);
            }
        });

        queryBt.setText("Query");
        queryBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queryBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ChineseNameField)
                                    .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seriousLevelComboBox, 0, 1, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 272, Short.MAX_VALUE)))
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(recordBt)
                        .addGap(77, 77, 77)
                        .addComponent(queryBt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateBt)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ChineseNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seriousLevelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recordBt)
                    .addComponent(queryBt)
                    .addComponent(updateBt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void recordBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordBtActionPerformed
        // TODO add your handling code here:
        disease = new Disease();
        diseaseLinker = new DiseaseLinker();
        disease.setDiseaseName(nameField.getText());
        disease.setDiseaseChineseName(ChineseNameField.getText());
        disease.setDiseaseDescription(descriptField.getText());
        disease.setDiseaseChineseDescrip(chineseDescripField.getText());
        disease.setSeriousLevel(seriousLevelComboBox.getSelectedIndex() + 1);
        diseaseLinker.setDisease(disease);        
        String hint = "Add disease to database " + ((diseaseLinker.addDisease())? "succeed!" : "failed");
        JOptionPane.showMessageDialog(this, hint);
    }//GEN-LAST:event_recordBtActionPerformed

    private void updateBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "You might query before update.");
        disease = new Disease();
        diseaseLinker = new DiseaseLinker();
        disease.setDiseaseName(nameField.getText());
        disease = diseaseLinker.readDiseaseInfoFromDB(disease.getDiseaseName(), false);
        disease.setDiseaseChineseName(ChineseNameField.getText());
        disease.setDiseaseDescription(descriptField.getText());
        disease.setDiseaseChineseDescrip(chineseDescripField.getText());
        disease.setSeriousLevel(seriousLevelComboBox.getSelectedIndex() + 1);
        diseaseLinker.setDisease(disease);
        
        String hint = "Update disease to database " + ((diseaseLinker.updateDiseaseInfo())? "succeed!" : "failed");
        JOptionPane.showMessageDialog(this, hint);
    }//GEN-LAST:event_updateBtActionPerformed

    private void queryBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queryBtActionPerformed
        // TODO add your handling code here:
        disease = new Disease();
        diseaseLinker = new DiseaseLinker();
        disease.setDiseaseName(nameField.getText());
        disease.setDiseaseChineseName(ChineseNameField.getText());
        
        if( (disease.getDiseaseChineseName() != null) && (! disease.getDiseaseChineseName().split(" ").equals(" ")) )
             disease = diseaseLinker.readDiseaseInfoFromDB(disease.getDiseaseChineseName(), true);
        else
             disease = diseaseLinker.readDiseaseInfoFromDB(disease.getDiseaseName(), false);
        
        nameField.setText(disease.getDiseaseName());
        ChineseNameField.setText(disease.getDiseaseChineseName());
        descriptField.setText(disease.getDiseaseDescription());
        chineseDescripField.setText(disease.getDiseaseChineseDescrip());
    }//GEN-LAST:event_queryBtActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.removeAll();
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    public void displayFrame() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiseaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiseaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiseaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiseaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new DiseaseFrame().setVisible(true);
        });
    }

    //User specified variables, can modify:
    private DiseaseLinker diseaseLinker;
    private Disease disease;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ChineseNameField;
    private javax.swing.JTextArea chineseDescripField;
    private javax.swing.JTextArea descriptField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton queryBt;
    private javax.swing.JButton recordBt;
    private javax.swing.JComboBox<String> seriousLevelComboBox;
    private javax.swing.JButton updateBt;
    // End of variables declaration//GEN-END:variables
}
