/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjectFrames;

import BasicEntities.ActualDiet;
import BasicEntities.AmountUnit;
import BasicEntities.FoodDrink;
import DBLinkers.ActualDietLinker;
import DBLinkers.AmountMeasurementLinker;
import DBLinkers.FoodDrinkLinker;
import DBLinkers.FoodImageLinker;
import java.io.File;
import java.sql.SQLException;
import java.util.LinkedList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author SamY
 */
public class RUserRecordDiet extends javax.swing.JFrame {

    /**
     * Creates new form RUserRecordDiet
     */
    public RUserRecordDiet(int rUserID) {
        this.rUserID = rUserID;        
        foodDrink = new FoodDrink();
        updateFoodDrinkList();    
        updateAmountUnitList();
        initComponents();
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }

    private void updateFoodDrinkList() {
        foodDrinkLinker = new FoodDrinkLinker();
        foodDrinkList = foodDrinkLinker.getAllFoodDrink();
        foodDrinkStrList = new LinkedList<>();
        foodDrinkList.forEach((fd) -> {
            foodDrinkStrList.add(fd.getFoodDrinkName() + "-" + fd.getFoodDrinkChinesename());
        });
        foodDrinkStrs = (String[]) foodDrinkStrList.toArray(new String[foodDrinkStrList.size()]);
        if (foodJCombo != null) {
            foodJCombo.setModel(new javax.swing.DefaultComboBoxModel<>(foodDrinkStrs));
        }
    }
    
    private void updateAmountUnitList(){
        amountMeasurementLinker = new AmountMeasurementLinker();
        amountUnitList = amountMeasurementLinker.getAllMeasurements();
        amountUnitStrList = new LinkedList<>();
        
        amountUnitList.forEach((au) -> {
            amountUnitStrList.add(au.getMeasurementName() + "-" + au.getMeasurementChineseName());
        });
        amountUnitStrs = (String[]) amountUnitStrList.toArray(new String[amountUnitStrList.size()]);
        if (amountCombo != null) {
            amountCombo.setModel(new javax.swing.DefaultComboBoxModel<>(amountUnitStrs));
        }
    }//end method
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        foodJCombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        addBt = new javax.swing.JButton();
        imgLabel = new javax.swing.JLabel();
        amountField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        amountCombo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        recordBt = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        // 将组件添加到父容器的代码 - 此处未显示
        foodJCombo.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        foodJCombo.setModel(new javax.swing.DefaultComboBoxModel<>(foodDrinkStrs));
        foodJCombo.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        foodJCombo.setToolTipText("If food not found, input in the text below:");
        foodJCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                foodJComboItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Gautami", 1, 24)); // NOI18N
        jLabel1.setText("Name of the food / drink:");

        addBt.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        addBt.setText("What I ate / drunk is not here");
        addBt.setToolTipText("If food / drink is not found, click this.");
        addBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtActionPerformed(evt);
            }
        });

        foodDrink = foodDrinkList.get(0);

        FoodImageLinker picLinker = new FoodImageLinker();
        //TODO add your handling code here:

        try {
            imgPath = picLinker.readPicToMemory(foodDrink.getFoodDrinkID());
            File f = new File(imgPath);
            imgLabel.setIcon(new ImageIcon(imgPath));
            imgLabel.setHorizontalAlignment(JLabel.CENTER);
            f.delete();
        } catch (SQLException ex) {
            //It happens, doing nothing.
            imgLabel.setIcon(null);
        }//end try-catch
        imgLabel.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        imgLabel.setText("Image of this is \ncurrently not available.");

        amountField.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        amountField.setText("A number");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel2.setText("You Eat:");

        amountCombo.setFont(new java.awt.Font("方正兰亭超细黑简体", 3, 24)); // NOI18N
        amountCombo.setModel(new javax.swing.DefaultComboBoxModel<>(amountUnitStrs));
        amountCombo.setToolTipText("Numerical means u know exactly how many grams you ate.");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel3.setText("of it.");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 3, 36)); // NOI18N
        jLabel4.setText("Portion:");
        jLabel4.setToolTipText("Portion is a particular word in health and nutrion means amount.");

        recordBt.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        recordBt.setText("Record it");
        recordBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordBtActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel5.setText("unit(s) / g");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBt)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(145, 145, 145)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(imgLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 365, Short.MAX_VALUE)
                            .addComponent(foodJCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5))
                            .addComponent(jLabel3)
                            .addComponent(amountCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(recordBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foodJCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addComponent(amountCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(24, 24, 24)
                        .addComponent(recordBt)))
                .addGap(18, 18, 18)
                .addComponent(addBt)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void foodJComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_foodJComboItemStateChanged
        // TODO add your handling code here:
        // TODO add your handling code here:
        foodDrink = foodDrinkList.get(foodJCombo.getSelectedIndex());
        
        FoodImageLinker picLinker = new FoodImageLinker();
        //TODO add your handling code here:
        
        try {
            imgPath = picLinker.readPicToMemory(foodDrink.getFoodDrinkID());
            File f = new File(imgPath);
            imgLabel.setIcon(new ImageIcon(imgPath));
            imgLabel.setHorizontalAlignment(JLabel.CENTER);
            f.delete();
        } catch (SQLException ex) {
            //It happens, doing nothing.
            imgLabel.setIcon(null);
        }//end try-catch
    }//GEN-LAST:event_foodJComboItemStateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void addBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtActionPerformed
        // TODO add your handling code here:
        FoodDrinkFrame fdf = new FoodDrinkFrame();
        fdf.displayFrame();
        JOptionPane.showMessageDialog(this, "Open this dialog again to record it after you finish.");
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_addBtActionPerformed

    private void recordBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordBtActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Simply select another item and record the portion,"
              + "\nif you eat more than one food. ");
        
        actualDiet = new ActualDiet();
        actualDiet.setUserID(rUserID);
        foodDrink = foodDrinkList.get(foodJCombo.getSelectedIndex());
        actualDiet.setFoodDrinkID(foodDrink.getFoodDrinkID());
        amountUnit = amountUnitList.get(amountCombo.getSelectedIndex());
        actualDiet.setMeasurementID(amountUnit.getMeasurementID());
        actualDiet.setUnitAmount(Double.parseDouble(amountField.getText()));
        
        actualDietLinker = new ActualDietLinker();
        actualDietLinker.writeUserActualDiet(rUserID, actualDiet);
    }//GEN-LAST:event_recordBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public void displayFrame() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RUserRecordDiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RUserRecordDiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RUserRecordDiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RUserRecordDiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RUserRecordDiet(rUserID).setVisible(true);
            }
        });   

    }
    
    private int rUserID;
    //User variables, can be modified.
    private FoodDrinkLinker foodDrinkLinker;
    private FoodDrink foodDrink;    
    private LinkedList<FoodDrink> foodDrinkList;
    private LinkedList<String> foodDrinkStrList;
    private String[] foodDrinkStrs;
    private String imgPath;
    
    private AmountUnit amountUnit;
    private AmountMeasurementLinker amountMeasurementLinker;
    private LinkedList<AmountUnit> amountUnitList;
    private LinkedList<String> amountUnitStrList;
    private String[] amountUnitStrs;
    
    private ActualDietLinker actualDietLinker;
    private ActualDiet actualDiet;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBt;
    private javax.swing.JComboBox<String> amountCombo;
    private javax.swing.JTextField amountField;
    private javax.swing.JComboBox<String> foodJCombo;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton recordBt;
    // End of variables declaration//GEN-END:variables
}
