package ProjectFrames;

import javax.swing.JOptionPane;
import DBLinkers.RegisteredUserLinker;
import DBLinkers.RUserBMILinker;
import BasicEntities.RegisteredUser;
import BasicEntities.RegisteredUserBMI;
import javax.swing.JFrame;

/**
 *
 * @author Administrator
 */
public class RUserBMIFrame extends JFrame{

    /**
     * Creates new form RUserBMIFrame
     * @param rUserID
     */
    public RUserBMIFrame(int rUserID) {
        reloadUserBMIData(rUserID);
        initComponents();
        rUserLinker = new RegisteredUserLinker();
        usernameDisplayLabel.setText(rUserLinker.readSingleUserFromDB(rUserID).getUsername());
        refreshUserBMIStatus();
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }//end constructor
    
    private void reloadUserBMIData(int rUserID){
        this.rUserID = rUserID;
        rUserLinker = new RegisteredUserLinker();
        rUserBMILinker = new RUserBMILinker();
        rUser = rUserLinker.readSingleUserFromDB(rUserID);
        rUserBMI = rUserBMILinker.readAvgRUserBMIFromDB(rUserID);
    }//end method

    private void refreshUserBMIStatus() {
        if (rUserBMI == null) {
            rUserBMI = new RegisteredUserBMI();
            rUserBMI.setHeight(1.75);
            rUserBMI.setWeight(67);
            JOptionPane.showMessageDialog(this, "Your record is cleared, please input new record!", "Warning!", JOptionPane.WARNING_MESSAGE);
        }//end else

        avgHeightDisplayLabel.setText(String.format("%.2f", rUserBMI.getHeight()));
        avgWeightDisplayLabel.setText(String.format("%.2f", rUserBMI.getWeight()));
        BMIavg = rUserBMI.getWeight() / Math.pow(rUserBMI.getHeight(), 2);
        BMIDisplayLabel.setText(String.format("%.2f", BMIavg));
        bodyPropDisplayLabel.setText(judgeBodyStatus(BMIavg));
    }//end method

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameDisplayLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        avgHeightLabel = new javax.swing.JLabel();
        avgWeightLabel = new javax.swing.JLabel();
        avgHeightDisplayLabel = new javax.swing.JLabel();
        avgWeightDisplayLabel = new javax.swing.JLabel();
        heightField = new javax.swing.JTextField();
        weightField = new javax.swing.JTextField();
        newHeightLabel = new javax.swing.JLabel();
        newWeightLabel = new javax.swing.JLabel();
        recordBt = new javax.swing.JButton();
        cleanBt = new javax.swing.JButton();
        chineseVersionBt = new javax.swing.JButton();
        BMILabel = new javax.swing.JLabel();
        BMIDisplayLabel = new javax.swing.JLabel();
        bodyPropertyLabel = new javax.swing.JLabel();
        bodyPropDisplayLabel = new javax.swing.JLabel();
        newBMILabel = new javax.swing.JLabel();
        newBMIDisplayLabel = new javax.swing.JLabel();
        newBodyStatusLabel = new javax.swing.JLabel();
        newBodyStatusDisplayLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        usernameDisplayLabel.setFont(new java.awt.Font("黑体", 0, 24)); // NOI18N
        usernameDisplayLabel.setText("User");
        usernameDisplayLabel.setToolTipText("");

        usernameLabel.setFont(new java.awt.Font("黑体", 0, 24)); // NOI18N
        usernameLabel.setText("Username:");

        avgHeightLabel.setFont(new java.awt.Font("黑体", 0, 24)); // NOI18N
        avgHeightLabel.setText("Height Avg(m):");
        avgHeightLabel.setToolTipText("Display your recent height in average.");

        avgWeightLabel.setFont(new java.awt.Font("黑体", 0, 24)); // NOI18N
        avgWeightLabel.setText("Weight Avg(kg):");
        avgWeightLabel.setToolTipText("Display your recent weight in average.");

        avgHeightDisplayLabel.setFont(new java.awt.Font("黑体", 0, 24)); // NOI18N
        avgHeightDisplayLabel.setText("1.75");

        avgWeightDisplayLabel.setFont(new java.awt.Font("黑体", 0, 24)); // NOI18N
        avgWeightDisplayLabel.setText("67 kg");

        heightField.setFont(new java.awt.Font("黑体", 0, 24)); // NOI18N
        heightField.setText("1.75");
        heightField.setToolTipText("Input your new height measuring record here.");

        weightField.setFont(new java.awt.Font("黑体", 0, 24)); // NOI18N
        weightField.setText("67");
        weightField.setToolTipText("Input your new weight measuring record here");

        newHeightLabel.setFont(new java.awt.Font("黑体", 0, 24)); // NOI18N
        newHeightLabel.setText("New Height(m):");
        newHeightLabel.setToolTipText("");

        newWeightLabel.setFont(new java.awt.Font("黑体", 0, 24)); // NOI18N
        newWeightLabel.setText("New Weight(kg):");

        recordBt.setFont(new java.awt.Font("黑体", 0, 24)); // NOI18N
        recordBt.setText("Record");
        recordBt.setToolTipText("Record your recent height and weight.");
        recordBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordBtActionPerformed(evt);
            }
        });

        cleanBt.setFont(new java.awt.Font("黑体", 0, 24)); // NOI18N
        cleanBt.setText("Clean");
        cleanBt.setToolTipText("Clean all of your recent records, you may do it if you find the measurements are not accurate.");
        cleanBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanBtActionPerformed(evt);
            }
        });

        chineseVersionBt.setFont(new java.awt.Font("黑体", 0, 24)); // NOI18N
        chineseVersionBt.setText("中文版");
        chineseVersionBt.setToolTipText("切换至中文版");
        chineseVersionBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chineseVersionBtActionPerformed(evt);
            }
        });

        BMILabel.setFont(new java.awt.Font("黑体", 0, 24)); // NOI18N
        BMILabel.setText("BMI:");
        BMILabel.setToolTipText("Your BMI accroding to at most recent 7 average meaurement of your weight and your height.");

        BMIDisplayLabel.setFont(new java.awt.Font("黑体", 0, 24)); // NOI18N
        BMIDisplayLabel.setText("21.87");

        bodyPropertyLabel.setFont(new java.awt.Font("黑体", 0, 24)); // NOI18N
        bodyPropertyLabel.setText("Body status:");
        bodyPropertyLabel.setToolTipText("Your body status in average, can be too thin, normal, too fat and obesity.");

        bodyPropDisplayLabel.setFont(new java.awt.Font("黑体", 0, 24)); // NOI18N
        bodyPropDisplayLabel.setText("Normal");

        newBMILabel.setFont(new java.awt.Font("黑体", 0, 24)); // NOI18N
        newBMILabel.setText("New BMI:");
        newBMILabel.setToolTipText("Your BMI, automatically calculated.");

        newBMIDisplayLabel.setFont(new java.awt.Font("黑体", 0, 24)); // NOI18N
        newBMIDisplayLabel.setText("21.87");

        newBodyStatusLabel.setFont(new java.awt.Font("黑体", 0, 24)); // NOI18N
        newBodyStatusLabel.setText("New Body Status:");
        newBodyStatusLabel.setToolTipText("Your body status this time, can be too thin, normal, too fat and obesity.");

        newBodyStatusDisplayLabel.setFont(new java.awt.Font("黑体", 0, 24)); // NOI18N
        newBodyStatusDisplayLabel.setText("Normal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(usernameDisplayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(358, 358, 358))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chineseVersionBt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(127, 127, 127)
                                        .addComponent(cleanBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(BMILabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(99, 99, 99))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(avgHeightLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(9, 9, 9))
                                            .addComponent(avgWeightLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(bodyPropertyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(27, 27, 27)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(avgHeightDisplayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(avgWeightDisplayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(9, 9, 9))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(BMIDisplayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(9, 9, 9))
                                            .addComponent(bodyPropDisplayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(newHeightLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(newWeightLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(9, 9, 9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(newBMILabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(72, 72, 72))
                                    .addComponent(newBodyStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(heightField)
                                        .addGap(12, 12, 12))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(weightField)
                                        .addGap(12, 12, 12))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(newBMIDisplayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(9, 9, 9))
                                    .addComponent(newBodyStatusDisplayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(365, 365, 365)
                                .addComponent(recordBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameDisplayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(heightField)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newHeightLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(avgHeightLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(avgHeightDisplayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6)))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(weightField)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newWeightLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(avgWeightLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(avgWeightDisplayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newBMILabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newBMIDisplayLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BMILabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BMIDisplayLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newBodyStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newBodyStatusDisplayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bodyPropertyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bodyPropDisplayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cleanBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(recordBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chineseVersionBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chineseVersionBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chineseVersionBtActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "建设中，敬请期待！");
    }//GEN-LAST:event_chineseVersionBtActionPerformed

    private void recordBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordBtActionPerformed
        // TODO add your handling code here:
        rUserBMI = new RegisteredUserBMI();
        rUserBMI.setRUserID(rUserID);
        rUserBMI.setHeight(Double.parseDouble(heightField.getText()));
        rUserBMI.setWeight(Double.parseDouble(weightField.getText()));
        rUserBMILinker = new RUserBMILinker();
        BMIavg = rUserBMI.getWeight() / Math.pow(rUserBMI.getHeight(), 2);
        newBMIDisplayLabel.setText(String.format("%.2f", BMIavg));
        newBodyStatusDisplayLabel.setText(judgeBodyStatus(BMIavg));
        rUserBMILinker.setRUserBMI(rUserBMI);
        String hint = "Add your record " + 
                ( (rUserBMILinker.addUserBMIToDB())? " success. " : " fails. ");
        JOptionPane.showMessageDialog(this, hint);
        reloadUserBMIData(rUserID);
        refreshUserBMIStatus();
    }//GEN-LAST:event_recordBtActionPerformed

    private void cleanBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanBtActionPerformed
        // TODO add your handling code here:
        rUserBMI = new RegisteredUserBMI();
        rUserBMI.setRUserID(rUserID);
        boolean cleanSuccess = rUserBMILinker.cleanUserBMIInfo();
        String hint = "Clean your record "
                + (cleanSuccess ? " success. " : " fails. ");

        JOptionPane.showMessageDialog(this, hint);

        if (cleanSuccess)
            JOptionPane.showMessageDialog(this, "Your record is cleared, please input new record!", "Warning!", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_cleanBtActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     */
    public void displayFrame() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RUserBMIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RUserBMIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RUserBMIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RUserBMIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new RUserBMIFrame(rUserID).setVisible(true);
        });
    }
    
    public String judgeBodyStatus(double BMI){
        if(BMI <= 18.5)
            return "Too thin";
        else if(BMI <= 24)
            return "Normal";
        else if(BMI <= 27.5)
            return "Too fat";
        else
            return "Obesity";
    }//end method

    //User add variable, can modify:
    private int rUserID;
    private double BMIavg, BMInow;
    private RegisteredUserLinker rUserLinker;
    private RUserBMILinker rUserBMILinker;
    private RegisteredUser rUser;
    private RegisteredUserBMI rUserBMI;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BMIDisplayLabel;
    private javax.swing.JLabel BMILabel;
    private javax.swing.JLabel avgHeightDisplayLabel;
    private javax.swing.JLabel avgHeightLabel;
    private javax.swing.JLabel avgWeightDisplayLabel;
    private javax.swing.JLabel avgWeightLabel;
    private javax.swing.JLabel bodyPropDisplayLabel;
    private javax.swing.JLabel bodyPropertyLabel;
    private javax.swing.JButton chineseVersionBt;
    private javax.swing.JButton cleanBt;
    private javax.swing.JTextField heightField;
    private javax.swing.JLabel newBMIDisplayLabel;
    private javax.swing.JLabel newBMILabel;
    private javax.swing.JLabel newBodyStatusDisplayLabel;
    private javax.swing.JLabel newBodyStatusLabel;
    private javax.swing.JLabel newHeightLabel;
    private javax.swing.JLabel newWeightLabel;
    private javax.swing.JButton recordBt;
    private javax.swing.JLabel usernameDisplayLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField weightField;
    // End of variables declaration//GEN-END:variables
}
