/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjectFrames;

import BasicEntities.FoodDrink;
import DBLinkers.FoodImageLinker;
import FunctionalClasses.RecommendDishes;
import java.io.File;
import java.sql.SQLException;
import java.util.LinkedList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Administrator
 */
public class RUserRecommendFoodFrame extends javax.swing.JFrame {

    /**
     * Creates new form RuserRecommendFoodFrame
     * @param rUserID
     */
    public RUserRecommendFoodFrame(int rUserID) {
        this.rUserID = rUserID;
        recommendDishes = new RecommendDishes(rUserID);
        recommendFoodDrinkList = recommendDishes.getRecommendFoodListForMeal();
        foodDrinkCount = 0;
        initComponents();
        updateInfoLabels();
        
        RUserRecommendFoodFrameTotal totalInfo = new RUserRecommendFoodFrameTotal(recommendFoodDrinkList);
        totalInfo.displayFrame();
        
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }//end constructor

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        againBt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        foodNumLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        proteinLabel = new javax.swing.JLabel();
        fatLabel = new javax.swing.JLabel();
        carboLabel = new javax.swing.JLabel();
        calLabel = new javax.swing.JLabel();
        vitaminLabel = new javax.swing.JLabel();
        mineralLabel = new javax.swing.JLabel();
        waterLabel = new javax.swing.JLabel();
        imgLabel = new javax.swing.JLabel();
        nextBt = new javax.swing.JButton();
        previousBt = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        chNameLabel = new javax.swing.JLabel();
        totalBt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        againBt.setFont(new java.awt.Font("Raavi", 1, 24)); // NOI18N
        againBt.setText("Recommend Again");
        againBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                againBtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        jLabel1.setText("Food Num:");

        foodNumLabel.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        foodNumLabel.setText("1");

        jLabel2.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        jLabel2.setText("Protein (g):");

        jLabel3.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        jLabel3.setText("Fat (g):");

        jLabel4.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        jLabel4.setText("Carbo (g):");
        jLabel4.setToolTipText("Carbo stands for carbohydrate");

        jLabel5.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        jLabel5.setText("Cal (g):");
        jLabel5.setToolTipText("Cal stands for calorie");

        jLabel6.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        jLabel6.setText("Vitamin (g):");

        jLabel7.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        jLabel7.setText("Mineral (g):");

        jLabel8.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        jLabel8.setText("Water (g):");

        proteinLabel.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        proteinLabel.setText("jLabel9");

        fatLabel.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        fatLabel.setText("jLabel9");

        carboLabel.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        carboLabel.setText("jLabel9");

        calLabel.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        calLabel.setText("jLabel9");

        vitaminLabel.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        vitaminLabel.setText("jLabel9");

        mineralLabel.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        mineralLabel.setText("jLabel9");

        waterLabel.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        waterLabel.setText("jLabel9");

        nextBt.setFont(new java.awt.Font("Raavi", 1, 24)); // NOI18N
        nextBt.setText("Next");
        nextBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtActionPerformed(evt);
            }
        });

        previousBt.setFont(new java.awt.Font("Raavi", 1, 24)); // NOI18N
        previousBt.setText("Previous");
        previousBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousBtActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        jLabel10.setText("Food Name:");

        jLabel11.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        jLabel11.setText("Chinese Name:");

        nameLabel.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        nameLabel.setText("jLabel12");

        chNameLabel.setFont(new java.awt.Font("方正兰亭超细黑简体", 1, 24)); // NOI18N
        chNameLabel.setText("jLabel12");

        totalBt.setFont(new java.awt.Font("Raavi", 1, 24)); // NOI18N
        totalBt.setText("Total");
        totalBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(againBt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(foodNumLabel)
                    .addComponent(proteinLabel)
                    .addComponent(fatLabel)
                    .addComponent(nameLabel)
                    .addComponent(carboLabel)
                    .addComponent(chNameLabel)
                    .addComponent(calLabel)
                    .addComponent(vitaminLabel)
                    .addComponent(mineralLabel)
                    .addComponent(waterLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(nextBt, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(previousBt)
                        .addGap(18, 18, 18)
                        .addComponent(totalBt))
                    .addComponent(imgLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(againBt)
                    .addComponent(nextBt)
                    .addComponent(previousBt)
                    .addComponent(totalBt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(foodNumLabel))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(nameLabel))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(chNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(proteinLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(fatLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(carboLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(calLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(vitaminLabel))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(mineralLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(waterLabel)))
                    .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateInfoLabels(){
        foodNumLabel.setText( (foodDrinkCount + 1) + "");
        FoodDrink fd = recommendFoodDrinkList.get(foodDrinkCount);
        nameLabel.setText(fd.getFoodDrinkName());
        chNameLabel.setText(fd.getFoodDrinkChinesename());
        proteinLabel.setText(String.format("%.2f", fd.getProtein()));
        fatLabel.setText(String.format("%.2f",fd.getFat()));
        carboLabel.setText(String.format("%.2f",fd.getCarbohydrate()));
        calLabel.setText(String.format("%.2f",fd.getCalorie()));
        mineralLabel.setText(String.format("%.2f",fd.getMineral()));
        vitaminLabel.setText(String.format("%.2f",fd.getVitamin()));
        waterLabel.setText(String.format("%.2f",fd.getWater()));
        
        FoodImageLinker picLinker = new FoodImageLinker();
        //TODO add your handling code here:
        
        try {
            String imgPath = picLinker.readPicToMemory(fd.getFoodDrinkID());
            File f = new File(imgPath);
            imgLabel.setIcon(new ImageIcon(imgPath));
            imgLabel.setHorizontalAlignment(JLabel.CENTER);
            f.delete();
        } catch (SQLException ex) {
            //It happens, doing nothing.
            imgLabel.setIcon(null);
        }//end try-catch
    }//end method
    
    private void againBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_againBtActionPerformed
        // TODO add your handling code here:
        recommendDishes = new RecommendDishes(rUserID);
        recommendFoodDrinkList = recommendDishes.getRecommendFoodListForMeal();
        updateInfoLabels();
    }//GEN-LAST:event_againBtActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void nextBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtActionPerformed
        // TODO add your handling code here:
        foodDrinkCount ++;        
        if(foodDrinkCount == 5) foodDrinkCount = 0;        
        updateInfoLabels();
    }//GEN-LAST:event_nextBtActionPerformed

    private void previousBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousBtActionPerformed
        // TODO add your handling code here:
         foodDrinkCount --;        
        if(foodDrinkCount == -1) foodDrinkCount = 4;        
        updateInfoLabels();
    }//GEN-LAST:event_previousBtActionPerformed

    private void totalBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalBtActionPerformed
        // TODO add your handling code here:
        RUserRecommendFoodFrameTotal totalInfo = new RUserRecommendFoodFrameTotal(recommendFoodDrinkList);
        totalInfo.displayFrame();
    }//GEN-LAST:event_totalBtActionPerformed

    public void displayFrame() {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new RUserRecommendFoodFrame(rUserID).setVisible(true);
        });
    }
    
    private final int rUserID;
    private int foodDrinkCount;
    private LinkedList<FoodDrink> recommendFoodDrinkList;
    private RecommendDishes recommendDishes;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton againBt;
    private javax.swing.JLabel calLabel;
    private javax.swing.JLabel carboLabel;
    private javax.swing.JLabel chNameLabel;
    private javax.swing.JLabel fatLabel;
    private javax.swing.JLabel foodNumLabel;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel mineralLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton nextBt;
    private javax.swing.JButton previousBt;
    private javax.swing.JLabel proteinLabel;
    private javax.swing.JButton totalBt;
    private javax.swing.JLabel vitaminLabel;
    private javax.swing.JLabel waterLabel;
    // End of variables declaration//GEN-END:variables
}
