package ProjectFrames;

import BasicEntities.Flavor;
import DBLinkers.TastesLinker;
import java.util.LinkedList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class TasteFrame extends javax.swing.JFrame{

    /**
     * Creates new form UserFlavorFrame
     * @param foodDrinkID
     */
    public TasteFrame(int foodDrinkID) {
        
        initComponents();
        this.foodDrinkID = foodDrinkID;
        tastesLinker = new TastesLinker();
        this.flavorList = tastesLinker.getFoodFlavorList(foodDrinkID);
        flavorList.forEach((f) -> {
            tickComboBox(f.getIdFlavor());
        }); //end loop
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }//end cons

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        recordBt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox9 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jCheckBox1.setText("Salty 咸");

        jCheckBox2.setText("Bitter 苦");

        jCheckBox3.setText("Sour 酸");

        jCheckBox4.setText("Sweet 甜");

        jCheckBox5.setText("Spicy 辣");

        jCheckBox6.setText("Unami 鲜");

        jCheckBox7.setText("Nice 香");

        jCheckBox8.setText("Light 淡");

        recordBt.setText("Record Flavor");
        recordBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordBtActionPerformed(evt);
            }
        });

        jLabel2.setText("Flavor of this food / drink:");

        jCheckBox9.setText("Greasy 腻");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox3)
                            .addComponent(jCheckBox4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox5)
                            .addComponent(jCheckBox6)
                            .addComponent(jCheckBox7)
                            .addComponent(jCheckBox8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox9)
                            .addComponent(recordBt)
                            .addComponent(jLabel2))
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(recordBt)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void recordBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordBtActionPerformed
        // TODO add your handling code here:
        checkFlavorList();
        tastesLinker = new TastesLinker();
        boolean recordSuccess = tastesLinker.storeUserFlavorInfo(flavorList, foodDrinkID);
        String hint = "Record food tastes information " + ( recordSuccess ? "succeed!" : "failed");
        JOptionPane.showMessageDialog(this, hint);
    }//GEN-LAST:event_recordBtActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.setVisible(false);
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    public void displayFrame() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TasteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TasteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TasteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TasteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TasteFrame(foodDrinkID).setVisible(true);
        });
    }//end method
    
    public void tickComboBox(int flavorID) {
        switch (flavorID) {
            case 1:
                jCheckBox1.setSelected(true);
                break;
            case 2:
                jCheckBox2.setSelected(true);
                break;
            case 3:
                jCheckBox3.setSelected(true);
                break;
            case 4:
                jCheckBox4.setSelected(true);
                break;
            case 5:
                jCheckBox5.setSelected(true);
                break;
            case 6:
                jCheckBox6.setSelected(true);
                break;
            case 7:
                jCheckBox7.setSelected(true);
                break;
            case 8:
                jCheckBox8.setSelected(true);
                break;
            default:
                jCheckBox9.setSelected(true);
                break;
        }//end switch
    }//end method
    
    public void checkFlavorList() {
        flavorList = new LinkedList<>();
        Flavor flavor;

        if (jCheckBox1.isSelected()) {
            flavor = new Flavor();
            flavor.setIdFlavor(1);
            flavorList.add(flavor);
        }

        if (jCheckBox2.isSelected()) {
            flavor = new Flavor();
            flavor.setIdFlavor(2);
            flavorList.add(flavor);
        }

        if (jCheckBox3.isSelected()) {
            flavor = new Flavor();
            flavor.setIdFlavor(3);
            flavorList.add(flavor);
        }

        if (jCheckBox4.isSelected()) {
            flavor = new Flavor();
            flavor.setIdFlavor(4);
            flavorList.add(flavor);
        }

        if (jCheckBox5.isSelected()) {
            flavor = new Flavor();
            flavor.setIdFlavor(5);
            flavorList.add(flavor);
        }

        if (jCheckBox6.isSelected()) {
            flavor = new Flavor();
            flavor.setIdFlavor(6);
            flavorList.add(flavor);
        }

        if (jCheckBox7.isSelected()) {
            flavor = new Flavor();
            flavor.setIdFlavor(7);
            flavorList.add(flavor);
        }

        if (jCheckBox8.isSelected()) {
            flavor = new Flavor();
            flavor.setIdFlavor(8);
            flavorList.add(flavor);
        }
    }//end method

    //User specified variable:
    //List what flavors does a typical food contain.
    private LinkedList<Flavor> flavorList;
    private final int foodDrinkID;
    private TastesLinker tastesLinker;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton recordBt;
    // End of variables declaration//GEN-END:variables
}//end class
